version: '3.8'

services:
  trivia:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TRIVIAAPP_CONFIG_PATH=docker.env
    ports:
      - "8082:8082"
    command: [ "/app/trivia" ]